### ISSUE TITLE
Typo under Configure-> Additional Methods

### ISSUE THREAD

**Issue by SoulofAkuma** [bootstrap-email/documentation-1.x#5]
The reset config method under Configure -> Additional Methods is written out as `BoostrapEmail.reset_config!` hence missing a "t" to spell `Bootstrap` and not `Boostrap`. Here's the URL to the site with the typo: [https://v1.bootstrapemail.com/docs/configure#additional-methods](https://v1.bootstrapemail.com/docs/configure#additional-methods). It's embarrassing to admit that I only encountered it because I copy-pasted :D

Also, can I configure the path to my custom CSS? The docs only state that the default path is the root path of the working directory, but I'd like to store it next to my emails. Anyway, thanks for all the work on this project!

**Comment by stuyam** [comment]
Fixed, thanks!
